### ISSUE TITLE
header values doubling

### ISSUE THREAD

**Issue by catroot** [saghul/uvwsgi#5]
using a single http_parser instance per connection improves speed, but causes multiplying of header values:

DATA SENT:
b'GET / HTTP/1.1\r\nHost: suite:5000\r\nConnection: keep-alive\r\nCache-Control: max-age=0\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate, sdch\r\nAccept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4\r\nCookie: i18next=en; csrftoken=kchG3ckgWkrdZZzk2z44SmPpWwDP1NbE; website_lang=ru_RU; _ga=GA1.1.1582135079.1464968679; session_id=78575ffe474fd3a007bcdfc340bb6ff48e0bf342\r\n\r\n'

GOT HEADERS:
IOrderedDict([('Host', 'suite:5000, suite:5000'), ('Connection', 'keep-alive, keep-alive'), ('Cache-Control', 'max-age=0, max-age=0'), ('Upgrade-Insecure-Requests', '1, 1'), ('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36, Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'), ('Accept-Encoding', 'gzip, deflate, sdch, gzip, deflate, sdch'), ('Accept-Language', 'ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4, ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4'), ('Cookie', 'i18next=en; csrftoken=kchG3ckgWkrdZZzk2z44SmPpWwDP1NbE; website_lang=ru_RU; _ga=GA1.1.1582135079.1464968679; session_id=78575ffe474fd3a007bcdfc340bb6ff48e0bf342, i18next=en; csrftoken=kchG3ckgWkrdZZzk2z44SmPpWwDP1NbE; website_lang=ru_RU; _ga=GA1.1.1582135079.1464968679; session_id=78575ffe474fd3a007bcdfc340bb6ff48e0bf342')])

I suggest to call __init__ on parser before passing data to it:

        if self.request is None:
            self.parser.__init__(kind=0)
            self.request = HTTPRequest(self)

**Comment by saghul** [comment]
Good catch. Can you send a Pull Request?

**Comment by catroot** [comment]
I spent almost a whole day to find whats wrong with it... So, of course, i can.

**Comment by saghul** [comment]
Cheers @catroot, merged the PR :-)
